package cg.app;

public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        cartesianPlane = new javax.swing.JPanel();
        statistics = new javax.swing.JPanel();
        size = new javax.swing.JLabel();
        inputCoordLabel = new javax.swing.JLabel();
        dcxLabel = new javax.swing.JLabel();
        dcxValue = new javax.swing.JLabel();
        dcyLabel = new javax.swing.JLabel();
        dcyValue = new javax.swing.JLabel();
        normCoordLabel = new javax.swing.JLabel();
        ndcxLabel = new javax.swing.JLabel();
        ndcxValue = new javax.swing.JLabel();
        ndcyLabel = new javax.swing.JLabel();
        ndcyValue = new javax.swing.JLabel();
        outputCoordLabel = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        xValue = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        yValue = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        draw = new javax.swing.JMenu();
        line = new javax.swing.JMenuItem();
        circle = new javax.swing.JMenuItem();
        heartBeat = new javax.swing.JMenu();
        transform = new javax.swing.JMenu();
        imageProcessing = new javax.swing.JMenu();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(leftPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 160, Short.MAX_VALUE));
        leftPanelLayout.setVerticalGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));

        javax.swing.GroupLayout cartesianPlaneLayout = new javax.swing.GroupLayout(cartesianPlane);
        cartesianPlane.setLayout(cartesianPlaneLayout);
        cartesianPlaneLayout.setHorizontalGroup(cartesianPlaneLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 716, Short.MAX_VALUE));
        cartesianPlaneLayout.setVerticalGroup(cartesianPlaneLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

        size.setText("Size: ");

        inputCoordLabel.setText("Input Coordinates:");

        dcxLabel.setText("DCX:");

        dcxValue.setText("0");

        dcyLabel.setText("DCY:");

        dcyValue.setText("0");

        normCoordLabel.setText("Normalized Coordinates:");

        ndcxLabel.setText("NDCX:");

        ndcxValue.setText("0");

        ndcyLabel.setText("NDCY:");

        ndcyValue.setText("0");

        outputCoordLabel.setText("Output Coordinates:");

        xLabel.setText("X:");

        xValue.setText("0");

        yLabel.setText("Y:");

        yValue.setText("0");

        javax.swing.GroupLayout statisticsLayout = new javax.swing.GroupLayout(statistics);
        statistics.setLayout(statisticsLayout);
        statisticsLayout.setHorizontalGroup(statisticsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statisticsLayout.createSequentialGroup().addContainerGap().addGroup(statisticsLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(statisticsLayout.createSequentialGroup().addGroup(statisticsLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(statisticsLayout.createSequentialGroup().addGroup(statisticsLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputCoordLabel)
                                        .addGroup(statisticsLayout.createSequentialGroup().addGap(6, 6, 6)
                                                .addGroup(statisticsLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(statisticsLayout.createSequentialGroup()
                                                                .addComponent(dcyLabel)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dcyValue))
                                                        .addGroup(statisticsLayout.createSequentialGroup()
                                                                .addComponent(dcxLabel)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dcxValue)))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(statisticsLayout.createSequentialGroup().addGroup(statisticsLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(normCoordLabel).addComponent(outputCoordLabel)
                                .addGroup(statisticsLayout.createSequentialGroup().addGap(6, 6, 6)
                                        .addGroup(statisticsLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(statisticsLayout.createSequentialGroup().addComponent(yLabel)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(yValue))
                                                .addGroup(statisticsLayout.createSequentialGroup().addComponent(xLabel)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(xValue))
                                                .addGroup(statisticsLayout.createSequentialGroup()
                                                        .addComponent(ndcyLabel)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ndcyValue))
                                                .addGroup(statisticsLayout.createSequentialGroup()
                                                        .addComponent(ndcxLabel)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(ndcxValue)))))
                                .addGap(0, 9, Short.MAX_VALUE)))));
        statisticsLayout.setVerticalGroup(statisticsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statisticsLayout.createSequentialGroup().addContainerGap()
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCoordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dcxLabel).addComponent(dcxValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dcyLabel).addComponent(dcyValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(normCoordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ndcxLabel).addComponent(ndcxValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ndcyLabel).addComponent(ndcyValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outputCoordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(xLabel).addComponent(xValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yLabel).addComponent(yValue))
                        .addContainerGap(249, Short.MAX_VALUE)));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
                rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        rightPanelLayout.createSequentialGroup().addContainerGap()
                                .addComponent(cartesianPlane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(statistics, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        rightPanelLayout
                .setVerticalGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statistics, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(
                                rightPanelLayout.createSequentialGroup().addContainerGap()
                                        .addComponent(cartesianPlane, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()));

        draw.setText("Draw");

        line.setText("Line");
        draw.add(line);

        circle.setText("Circle");
        draw.add(circle);

        menuBar.add(draw);

        heartBeat.setText("Heart Beat");
        menuBar.add(heartBeat);

        transform.setText("Transform");
        menuBar.add(transform);

        imageProcessing.setText("Image Processing");
        menuBar.add(imageProcessing);

        about.setText("About");
        menuBar.add(about);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6).addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JPanel cartesianPlane;
    private javax.swing.JMenuItem circle;
    private javax.swing.JLabel dcxLabel;
    private javax.swing.JLabel dcxValue;
    private javax.swing.JLabel dcyLabel;
    private javax.swing.JLabel dcyValue;
    private javax.swing.JMenu draw;
    private javax.swing.JMenu heartBeat;
    private javax.swing.JMenu imageProcessing;
    private javax.swing.JLabel inputCoordLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JMenuItem line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel ndcxLabel;
    private javax.swing.JLabel ndcxValue;
    private javax.swing.JLabel ndcyLabel;
    private javax.swing.JLabel ndcyValue;
    private javax.swing.JLabel normCoordLabel;
    private javax.swing.JLabel outputCoordLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel size;
    private javax.swing.JPanel statistics;
    private javax.swing.JMenu transform;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xValue;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yValue;
    // End of variables declaration//GEN-END:variables
}
